version: "3.7"
services:
  database:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./database:/var/lib/mysql:rw

volumes:
  database: